# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bundle-BDFOY
version:      20060527
version_from: lib/BDFOY.pm
installdirs:  site
requires:
    File::Find::Rule:              0
    Test::More:                    0
    Test::Pod:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
