--- #YAML:1.0
name:                Bundle-BDFOY
version:             20070101
abstract:            install all modules by BDFOY
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    File::Find::Rule:              0
    Test::More:                    0
    Test::Pod:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
